[package]
name = "TransferWorld"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
image = "0.25.6"
qrcode = "0.14.1"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
